/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_magicing_eigenndk_NDKUtils */

#ifndef _Included_com_magicing_eigenndk_NDKUtils
#define _Included_com_magicing_eigenndk_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_magicing_eigenndk_NDKUtils
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_magicing_eigenndk_NDKUtils_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_magicing_eigenndk_NDKUtils
 * Method:    bankcard
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_magicing_eigenndk_NDKUtils_bankcard
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
